[project]
name = "session1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "console>=0.9912",
    "datetime>=5.5",
    "rich>=14.3.3",
    "typer>=0.23.2",
]
